name = "salesignition"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
binding = "ASSETS"

[build]
command = "npm run build"
